openapi: 3.0.0
info:
  description: This API provides event stats
  version: "1.0.0"
  title: Stats API
  contact:
    email: ihussain7@my.bcit.ca

paths:
  /stats:
    get:
      summary: Gets the event stats
      operationId: app.get_stats
      description: Gets acceleration and environmental readings processsed statistics
      responses:
        '200':
          description: Successfully returned a list of acceleration and environmental events
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/ReadingStats'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    ReadingStats:
      required:
      - num_acceleration_readings
      - max_acceleration_speed_reading
      - max_acceleration_watt_hours_reading
      - num_environmental_readings
      - max_temp_reading
      properties:
        num_acceleration_readings:
          type: integer
          example: 500000
        max_acceleration_speed_reading:
          type: integer
          example: 150
        max_acceleration_watt_hours_reading:
          type: integer
          example: 180
        num_environmental_readings:
          type: integer
          example: 500000
        max_temp_reading:
          type: integer
          example: 30
      type: object