openapi: 3.0.0
info:
  description: This API receives efficiency data from electric vehicles.
  version: "1.0.0"
  title: Electric Vehicle Efficiency API
  contact:
    email: ihussain7@my.bcit.ca
tags:
  - name: efficiency
    description: Operations available to calculate efficiency
paths:
  /health:
    get:
      tags:
        - health
      summary: checks health of backend services
      operationId: app.get_health
      description: Gets health of backend services
      responses:
        '200':
          description: Successfully returned health check of backend services
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/HealthReading'
        
components:
  schemas:
    HealthReading:
      required:
        - receiver
        - storage
        - processing
        - audit
        - last_update
      properties:
        receiver:
          type: string
          example: Running
        storage:
          type: string
          example: Down
        processing:
          type: string
          example: Running
        audit:
          type: string
          example: Running
        last_update:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
      type: object